---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-rhacm-managedcluster-config-policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placementrule-configuration
  namespace: ns-rhacm-managedcluster-config-policies
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
    - key: usage
      operator: In
      values:
      - "configrequire"
