---
- name: Log in (obtain access token)
  k8s_auth:
    username: "{{ ocp_username }}"
    password: "{{ ocp_password }}"
    host: "{{ ocp_api_url }}"
    validate_certs: no
  register: ocp_auth_results

- name: Validate the state of the wanted Namespace
  k8s:
    name: "{{ ocp_namespace_name }}"
    api_version: v1
    kind: Namespace
    state: "{{ ocp_namespace_state }}"
    host: "{{ ocp_api_url }}"
    api_key: "{{ ocp_auth_results.ocp_auth.api_key }}"
    validate_certs: no
