apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-label-cluster
  namespace: ns-rhacm-managedcluster-config-policies   ## optional
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-label-cluster
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: cluster.open-cluster-management.io/v1
                kind: ManagedCluster
                metadata:
                  labels:
                    profile: demo
                  name: demo-cluster-label
                spec:
                  hubAcceptsClient: true
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-label-cluster
  namespace: ns-rhacm-managedcluster-config-policies
placementRef:
  name: placement-policy-label-cluster
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-label-cluster
  kind: Policy
  apiGroup: policy.open-cluster-management.io